# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-06 21:55
from __future__ import unicode_literals

import app.storages
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=128, verbose_name='first names')),
                ('last_name', models.CharField(max_length=128, verbose_name='last names')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Masculino'), (20, 'Femenino')], null=True, verbose_name='gender')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='city')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('avatar', models.ImageField(blank=True, help_text='300x300 pixels as light as possible.', null=True, upload_to=app.storages.random_upload_path)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_staff', models.BooleanField(default=False, help_text='Indicates id can enter the site of administration.', verbose_name='Staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last updated data')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'ordering': ['first_name', 'last_name'],
                'verbose_name_plural': 'users',
            },
        ),
    ]
